version: '3'

services:
  config-service:
    image: config-service-image
    container_name: config-server-container
    build: config-service/
    ports:
      - "8888:8888"
    hostname: config-service
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://services-registry:8761/eureka

  services-registry:
    image: services-registry-image
    container_name: eureka-server-container
    build: services-registry/
    ports:
      - "8761:8761"
    hostname: services-registry
    depends_on:
      - config-service
    environment:
      - WAIT_HOSTS=config-service:8888
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://services-registry:8761/eureka

  images-service:
    image: images-service-image
    container_name: images-service-container
    build: images-service/
    ports:
      - "8084:8084"
    hostname: images-service
    depends_on:
      - config-service
      - services-registry
    environment:
      - WAIT_HOSTS=config-service:8888, services-registry:8761
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://services-registry:8761/eureka
