version: '3'

services:
  config-service:
    image: config-service-image
    container_name: config-server-container
    build: config-service/
    ports:
      - "8888:8888"
    hostname: config-service
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://services-registry:8761/eureka

  services-registry:
    image: services-registry-image
    container_name: eureka-server-container
    build: services-registry/
    ports:
      - "8761:8761"
    hostname: services-registry
    depends_on:
      - config-service
    environment:
      - WAIT_HOSTS=config-service:8888
      - EUREKA_SERVER=http://services-registry:8761/eureka

  images-service:
    image: images-service-image
    container_name: images-service-container
    build: images-service/
    ports:
      - "8084:8084"
    hostname: images-service
    depends_on:
      - config-service
      - services-registry
    environment:
      - WAIT_HOSTS=config-service:8888, services-registry:8761
      - EUREKA_SERVER=http://services-registry:8761/eureka

  products-service:
    image: products-service-image
    container_name: products-service-container
    build: products-service/
    ports:
      - "8083:8083"
    hostname: products-service
    depends_on:
      - config-service
      - services-registry
    environment:
      - WAIT_HOSTS=config-service:8888, services-registry:8761
      - EUREKA_SERVER=http://services-registry:8761/eureka

  orders-service:
    image: orders-service-image
    container_name: orders-service-container
    hostname: orders-service
    ports:
      - "8081:8081"
    build: orders-service
    depends_on:
      - config-service
      - services-registry
    environment:
      - WAIT_HOSTS=config-service:8888, services-registry:8761
      - EUREKA_SERVER=http://services-registry:8761/eureka

  services-gateway:
    image: services-gateway-image
    container_name: services-gateway-container
    hostname: services-gateway
    ports:
    - "8000:8000"
    build: services-gateway
    depends_on:
      - config-service
      - services-registry
    environment:
      - WAIT_HOSTS=config-service:8888, services-registry:8761, orders-service:8081, products-service:8083
      - EUREKA_SERVER=http://services-registry:8761/eureka