server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registryFetchIntervalSeconds: 5
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    images-service:
      path: /images/**
      serviceId: images-service

    products-service:
      path: /products/**
      serviceId: products-service